### ISSUE TITLE
Build script fails

### ISSUE THREAD

**Issue by robsmith11** [Taaitaaiger/jl-sys#2]
I've installed the latest nightly rust and julia, defined `JL_PATH` and `LD_LIBRARY_PATH` as suggested, and installed llvm and clang, which seemed to be required, but the build of jl-sys is still failing:
```
   Compiling jl-sys v0.3.1
error: Only `-l` and `-L` flags are allowed in build script of `jl-sys v0.3.1`: `-L/home/me/julia/lib/`
```

Any idea what's wrong?

**Comment by Taaitaaiger** [comment]
That's odd, it seems to be complaining about a valid flag that is (and must be) used. What OS are you using, and how have you set those environment variables?

**Comment by robsmith11** [comment]
Arch Linux on Skylake Xeon.  I ran the build with

```
JL_PATH=/home/me/julia LD_LIBRARY_PATH=/home/me/julia/lib cargo build --release
```
I didn't look at the build script too closely but the error is confusing to me as well.  The environment variables seem to be picked up properly.

**Comment by Taaitaaiger** [comment]
Yeah, that should be fine. Could you try setting LD_LIBRARY_PATH to $LD_LIBRARY_PATH:/home/me/julia/lib? (I assume you've removed the version number from the extracted directory).

**Comment by robsmith11** [comment]
Sorry for the noise.  It turns out that I actually still had an old rust nightly installed.  After upgrading, it builds and works properly. :)

**Comment by Taaitaaiger** [comment]
Ah, that's good to hear :) if you run into any problems, don't hesitate to open a new issue.
